[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
imprint = "7rCC9dsbkGPx9Cu1k7eXx9AsGTQDmsi9wFhWp2yp446E"

[programs.devnet]
imprint = "7rCC9dsbkGPx9Cu1k7eXx9AsGTQDmsi9wFhWp2yp446E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ".keys/imprint-operator.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
setup-target = "node scripts/setup-target.js"
