[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
quarry_vault = "GYoRyyds3mQP2DKf2QLARgU6io8Fs6vYN4iGDJAsbk9b"
quarry_vault_fixed = "52EPhyEqX4v6k3X5cYAun72uNhQLcpgRfBF59MGTLH1W"
attacker_strategy = "HFvQEna9LSuPd2pNp1psDw1PT12h6bPnCRKsLzD3KTzS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"

